In [1]:
# import libraries
import pandas as pd

In [2]:
# connect to Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
# load olist_geolocation_dataset file
df = pd.read_csv('/content/drive/MyDrive/olist-ecommerce-analytics/processed_csv/olist_order_items_dataset.csv')

In [10]:
# check data types
df.dtypes

order_id                       object
order_item_id                   int64
product_id                     object
seller_id                      object
shipping_limit_date    datetime64[ns]
price                         float64
freight_value                 float64
dtype: object

In [14]:
# check if datetime conversion failed

df['shipping_limit_date'] = pd.to_datetime(
    df['shipping_limit_date'],
    errors='coerce'
)

In [15]:
# check if datetime conversion failed

df['shipping_limit_date'].isnull().sum()

np.int64(0)

In [21]:
# Explicit verification of columns that must not contain null values

df[
    [
        'order_id',
        'order_item_id',
        'product_id',
        'seller_id',
        'price',
        'freight_value',
        'shipping_limit_date'
    ]
].isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
price                  0
freight_value          0
shipping_limit_date    0
dtype: int64

In [17]:
# check keys and duplicate records

df.duplicated(subset=['order_id', 'order_item_id']).sum()

np.int64(0)

In [19]:
# validate minimum and maximum dates

df['shipping_limit_date'].min(), df['shipping_limit_date'].max()

(Timestamp('2016-09-19 00:15:34'), Timestamp('2020-04-09 22:35:08'))

In [20]:
# financial validations

df['price'].min(), df['price'].max()

(0.85, 6735.0)